### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by Inokinoki** [Inokinoki/QEFIEntryManager#10]

**Comment by hwittenborn** [comment]
I'm not sure what options you've looked at, but would [makedeb](https://makedeb.org) be of any interest? It's a project I've personally started, but I think it could provide a much easier format for managing a Debian package compared to standard Debian packaging.

**Comment by Inokinoki** [comment]
> I'm not sure what options you've looked at, but would [makedeb](https://makedeb.org) be of any interest? It's a project I've personally started, but I think it could provide a much easier format for managing a Debian package compared to standard Debian packaging.

Thanks for your proposition ! I'll give it a try

**Comment by Inokinoki** [comment]
FreeBSD pkg: https://cmake.org/cmake/help/latest/cpack_gen/freebsd.html
Windows: https://cmake.org/cmake/help/latest/cpack_gen/nsis.html
RPM: https://cmake.org/cmake/help/latest/cpack_gen/rpm.html
DEB: https://cmake.org/cmake/help/latest/cpack_gen/deb.html
